version '2.5.0'

services:
 db:
    image:mysql:5.7
    volumes:
        - db_data:/var/lib/mysql
    restart: always
    enviroment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
       
 wordpress:
  depends_on:    
   - db
   image: wordpress:latest
   ports:
    - "80:80"       
   restart: always
   enviroment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_USER: wordpress
    WORDPRESS_DB_PASSWORD: wordpress
    WORDPRESS_DB_NAME: wordpress
 volumes:
   db_data: {}